services:
  - type: web
    name: brf-v3-bybit-backtest
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
